# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

env:
  global:
    - secure: "HQesyukH609YyGTwO4VYRCOQzNJlRl1UGcwjnCjZUlPWWZdnua9AweXnugOiPCEbcYfWpqOe8SK4lcjbFRcGFUZ5IBTlErZ6l3t7WXQswJypbBGGQWD5Pvp10jULMfI9/hG3YAr/54NhysBOhCWRvs8Uj3/EQ2Gmk0R74+I8nPSpyfrPzZIfbwMFugAJo2PQJtcqsif87VJY+cbbMRa7Tzml01VrfvikRCZSO6WZmjpFy60iyqxhhqa1FWc57kxe/fQJGiR4kUDyGx5oUNY5R74/cF2ZABq+Ibhr1EVYaYDyn+UKtB/mbw8hbXIoRMDrA279jyNQDIgFVUd4Epsx3v03TkXycwIDjGDoHqO0hfGXi0s9EP1npLW6kT+JxQmVBc9nQxjgQSVHS+PWuuR397oOV4F4zyoL3kYdjCdhArLipVErOEol+DLn0ZLRWerhFNaLkNsELCbvVa2KWq1MjDlDNzj8tBS4N/3x+KH35mFPLqfRtEvk60N47qo1qHlS9nSa+PurbH2HZ13pLFcCOV5NEg+SkX3NrynHZEAf3wVH3wjLG1fMkMoLzDyRiKA8cEGI1dkrz7sxO5ZzQsufRHoBNxB67dRpEEhizvXq4/WrF1aAdjMpD1pZ5WNVMeC3dd0reidLHUUqkG/DvkY6R1cEXr56CGwdAhXFds/U8hQ="

language: node_js

node_js:
  - "4"

sudo: false
