# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

env:
  global:
    - secure: "ZTZCMJiiyxi6IxfVTt99B6b8nimdhJmQd5tGtDwyDKr/GQePePMVC3ieDexz4E0xUShQfsU162eX70F3h6zonP69by2nmVYNdjPuqcEwub7aAUYnlU0AvElFUpU5PEvv3Q6nusp8k16lgBcVCIGFyzWb0oWJ8h/1Ennon2rPBNOii+bffF230pDSrT3XPAyrqw4gvQ98BguiNGyPcVhdFhoYxdPQESFeYh+zcAQKXfmZr5l7oyjtNjyRbp/9cMz59nWO1YaBvi2j9cabQHPCw1zseLOWhev2p/PawrKaVAbJ/7yiELM2XLGhTufMN9oQ0vJv0J7Ts4+KcwgvblTmDLi+6uz3Fwy2pq6cIBq/EtgoAyNT6NSPpzg10SWxwDUocBpdu13ZnqLfC7GicDrxQAyXwP8qOeJAGU7OnSUgvjNvuznY6fFVhrhE8ybDJh3anlnBDBdrRZdqIDZKWp8cuvRaM6bvSiA3LV6NhMcG+dy5XUke8wEOtSP/IQirKBuKnynGKVGB0+KwuRQpccMC8OmjzF+rlExW7mM7BALenm5IN0kxB9PpXov7VNjH7hOVfsj8ZZulIQjwd3MEUX7pDRDZee0+AqTx3fJahatJIpPyZDFcI0PLuOfpaTxvoR4M2nyR6Y5Hw+YwGgRARUy1tBx8Hh3V7WX+ZUY7GMv9kUc="

language: node_js

node_js:
  - "node"

sudo: false
